# Generated by Django 3.1.7 on 2021-02-23 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('answer_choices', models.JSONField(blank=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poll.poll')),
            ],
        ),
    ]
