# Generated by Django 3.1.7 on 2021-02-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_pollquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollquestion',
            name='answer_choices',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
