# Generated by Django 3.1.7 on 2021-02-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20210223_1405'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='pollquestion',
            order_with_respect_to='poll',
        ),
    ]
